### ISSUE TITLE
review/rating system

### ISSUE THREAD

**Issue by brillout** [devarchy/website#1]
Quote of a [Reddit Comment](https://www.reddit.com/r/javascript/comments/504zmh/curated_list_of_react_components_libraries/d71h14h)

> What would be most useful to me is giving things a sort of rating of stability/scalability etc. 

 I'm recalcitrant to add ratings to open source libraries because
- doesn't feel good to negatively rate a pro bono open source project (maybe using positive wording could help here)
- open source projects can evolve very rapidly making old ratings irrelevant (maybe a system allowing the owner to flag negative comments as "addressed" could help)

On the other hand
- it would be convenient for users to be warned of major flaws (e.g. these major and fundamental flaws of AngularJS)

Future readers: thumbs up this post if you want this feature.

**Comment by chellew1222** [comment]
Thank you sir I do absolutely appreciate everything it's only anything that you do for me I do not know a lot about what we're going what is going on here but I'm going to be very green and I'm definitely up for trying and doing my best thank you very much sir

**Comment by brillout** [comment]
Not doing this in the short/mid term. Closing for now.
