### ISSUE TITLE
What is New Requests section?

### ISSUE THREAD

**Issue by saschwarz** [devarchy/website#11]
I'm a brand new visitor to the website, so maybe I have the same question(s) as other new people(?)

I don't understand what the New Requests section is for? If I click on the title it shows a project's details. Maybe add some text about what/how/why it exists and how things get added to it?

**Comment by brillout** [comment]
![screenshot 2017-04-13 at 03 20 14](https://cloud.githubusercontent.com/assets/1005638/24986078/7729cf16-1ff8-11e7-8ce1-3f8ad4b50f4f.png)

Better? I'm not a native English speak so I'm not sure if it's understable?

Thanks for opening the issue!
