### ISSUE TITLE
Firefox mouse to content scrolls back to top

### ISSUE THREAD

**Issue by mastacheata** [devarchy/website#16]
Select a category in the nav sidebar/tag list
-> The main part scrolls to the selected category

Move mouse from nav to main.

What should happen -> The main part stays where it scrolled to and I can look at the stuff there.
What actually happens -> As soon as I move the mouse across the vertical bar, the main part scrolls back to the top.

This happens in Firefox (54) and IE (11), but not in Chrome (58) or Edge (sry, no idea how to determine the version of that thing)

**Comment by brillout** [comment]
Thanks!

I could reproduce the issue and I'm looking into it.

**Comment by brillout** [comment]
Just pushed a fix live, should work again now. Thanks a lot for opening the issue!

**Comment by mastacheata** [comment]
Thanks a lot. Seems like the issue is gone for me as well.
