### ISSUE TITLE
Bookmarks support

### ISSUE THREAD

**Issue by gutenye** [devarchy/website#2]
Add ids to each section, so that we can bookmark any section. like `http://devarchy.com/react-components#data-table`

**Comment by brillout** [comment]
👍
thanks
(Note that you do that with the github readme, e.g. https://github.com/brillout/awesome-react-components#modals)

**Comment by brillout** [comment]
@gutenye With the release of the new version, every section has its own URL. E.g. https://devarchy.com/react/need/table

**Comment by gutenye** [comment]
@brillout  Thanks.
